<?php
/**
 * AppApiTest
 * PHP version 5
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Biwse API V1 Reference
 *
 * This API documentation generated from OpenAPI specification.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AppApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AppApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createAddress
     *
     * Create new address.
     *
     */
    public function testCreateAddress()
    {
    }

    /**
     * Test case for createInvoice
     *
     * Create invoice.
     *
     */
    public function testCreateInvoice()
    {
    }

    /**
     * Test case for createWalletInvoice
     *
     * Create wallet invoice.
     *
     */
    public function testCreateWalletInvoice()
    {
    }

    /**
     * Test case for getBalance
     *
     * Retrieve wallet balance.
     *
     */
    public function testGetBalance()
    {
    }

    /**
     * Test case for getInvoice
     *
     * Retreive invoice info.
     *
     */
    public function testGetInvoice()
    {
    }

    /**
     * Test case for sendOnePayment
     *
     * Send one payment.
     *
     */
    public function testSendOnePayment()
    {
    }

    /**
     * Test case for sendPayments
     *
     * Send payments.
     *
     */
    public function testSendPayments()
    {
    }
}
